<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds the addons catalog with every Intake addon + tier-included feature.
 *
 * Source of truth: intake-pricing-and-tiers.pdf feature dictionary (p.9) and
 * add-ons/onboarding section (p.6).
 *
 * Idempotent via updateOrInsert on `code`. Safe to re-run.
 */
class AddonCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $addons = [
            // COMMUNICATION ADD-ONS
            [
                'code' => 'sms_credits',
                'name' => 'SMS credits',
                'category' => 'communication',
                'description' => 'Twilio pass-through + 5% margin. Unlocks highest-response channel. No minimum, billed by usage.',
                'tooltip' => 'Text reminders and confirmations. 4x higher open rate than email.',
                'price_cents' => 0,
                'billing_cadence' => 'usage',
                'price_display_override' => '~$0.01/msg',
                'included_in_plans' => null,
                'sort_order' => 10,
                'is_new' => false,
            ],
            [
                'code' => 'ai_campaign_assist',
                'name' => 'AI campaign assist',
                'category' => 'communication',
                'description' => 'AI-generated winback, re-engagement, follow-up campaigns. Done in 10 seconds, pasted straight into the block builder.',
                'tooltip' => 'AI writes your winback, re-engagement, and follow-up campaigns for you.',
                'price_cents' => 4900,
                'billing_cadence' => 'monthly',
                'included_in_plans' => null,
                'sort_order' => 20,
            ],
            [
                'code' => 'branded_sms_sender',
                'name' => 'Branded SMS sender',
                'category' => 'communication',
                'description' => "Customers see your shop's name as SMS sender. Includes short code registration.",
                'tooltip' => 'Your shop name shows up as the SMS sender, not a generic number.',
                'price_cents' => 1900,
                'billing_cadence' => 'monthly',
                'included_in_plans' => null,
                'sort_order' => 30,
            ],
            [
                'code' => 'review_amplification',
                'name' => 'Review amplification',
                'category' => 'communication',
                'description' => 'Auto-push 5-star reviews to Google and Yelp. Turns satisfied customers into public advocates.',
                'tooltip' => 'Happy customers automatically get prompted to share their review publicly.',
                'price_cents' => 2900,
                'billing_cadence' => 'monthly',
                'included_in_plans' => null,
                'sort_order' => 40,
            ],

            // OPERATIONS ADD-ONS
            [
                'code' => 'waitlist',
                'name' => 'Waitlist',
                'category' => 'operations',
                'description' => 'Broadcast-offer waitlist. Customer cancels open up to notified waitlist entries; first to confirm wins.',
                'tooltip' => 'When a customer cancels, interested customers get notified. First to confirm the slot gets it.',
                'price_cents' => 1900,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['branded', 'scale', 'custom'],
                'sort_order' => 50,
                'is_new' => true,
            ],
            [
                'code' => 'additional_location',
                'name' => 'Additional location',
                'category' => 'operations',
                'description' => 'Add a new shop. Bulk discount: $19/mo at 5+. Cross-location profiles require Scale tier.',
                'tooltip' => 'Run another shop from the same Intake account.',
                'price_cents' => 2900,
                'billing_cadence' => 'monthly',
                'included_in_plans' => null,
                'sort_order' => 60,
            ],
            [
                'code' => 'additional_admin_user',
                'name' => 'Additional admin user',
                'category' => 'operations',
                'description' => "Beyond plan's included user count. Full access, role-scoped (staff/manager/owner).",
                'tooltip' => "Add more staff with role-scoped access beyond your plan's included seats.",
                'price_cents' => 1000,
                'billing_cadence' => 'monthly',
                'included_in_plans' => null,
                'sort_order' => 70,
            ],
            [
                'code' => 'loyalty_system',
                'name' => 'Loyalty & rewards',
                'category' => 'operations',
                'description' => 'Points, reward tiers, redemption. Huge retention lever across all tiers.',
                'tooltip' => 'Points accrue on every visit. Customers redeem for services or credit.',
                'price_cents' => 1900,
                'billing_cadence' => 'monthly',
                'included_in_plans' => null,
                'sort_order' => 80,
            ],
            [
                'code' => 'offline_sync',
                'name' => 'Offline sync resilience',
                'category' => 'operations',
                'description' => 'IndexedDB queue + service worker. Tenant admin keeps working through network outages. Included in Scale.',
                'tooltip' => "Keep working through network outages. Changes queue and sync when you're back online.",
                'price_cents' => 1900,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['scale', 'custom'],
                'sort_order' => 90,
                'is_new' => true,
            ],
            [
                'code' => 'api_write',
                'name' => 'API write access',
                'category' => 'operations',
                'description' => 'Programmatic write into Intake. Requires Scale tier (read access) first.',
                'tooltip' => 'Programmatically push data into Intake. For franchises and custom integrations.',
                'price_cents' => 9900,
                'billing_cadence' => 'monthly',
                'included_in_plans' => null,
                'sort_order' => 100,
            ],
            [
                'code' => 'priority_placement',
                'name' => 'Priority placement',
                'category' => 'operations',
                'description' => "Featured listing in Intake's industry directory. Higher visibility in search.",
                'tooltip' => "Featured placement in Intake's industry directory. Higher visibility in search.",
                'price_cents' => 2900,
                'billing_cadence' => 'monthly',
                'included_in_plans' => null,
                'sort_order' => 110,
            ],

            // TIER-INCLUDED FEATURES (is_self_serve=false, staff suppress-only)
            [
                'code' => 'sms_notifications',
                'name' => 'SMS notifications',
                'category' => 'feature',
                'description' => 'Text reminders and confirmations. Included in Branded and above.',
                'tooltip' => 'Text reminders and confirmations. 4x higher open rate than email.',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['branded', 'scale', 'custom'],
                'sort_order' => 200,
                'is_self_serve' => false,
            ],
            [
                'code' => 'abandoned_booking_recovery',
                'name' => 'Abandoned booking recovery',
                'category' => 'feature',
                'description' => "Auto-reaches out to customers who start booking but don't finish.",
                'tooltip' => "Auto-reaches out to customers who start booking but don't finish.",
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['branded', 'scale', 'custom'],
                'sort_order' => 210,
                'is_self_serve' => false,
            ],
            [
                'code' => 'winback_campaigns',
                'name' => 'Winback campaigns',
                'category' => 'feature',
                'description' => "Auto-email customers who haven't booked in 90 or 180 days.",
                'tooltip' => "Auto-email customers who haven't booked in 90 or 180 days.",
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['branded', 'scale', 'custom'],
                'sort_order' => 220,
                'is_self_serve' => false,
            ],
            [
                'code' => 'lifecycle_campaigns',
                'name' => 'Birthday & anniversary messages',
                'category' => 'feature',
                'description' => "Auto-send celebratory messages on customers' special dates.",
                'tooltip' => "Auto-send celebratory messages on customers' special dates.",
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['branded', 'scale', 'custom'],
                'sort_order' => 230,
                'is_self_serve' => false,
            ],
            [
                'code' => 'seasonal_campaigns',
                'name' => 'Seasonal campaigns',
                'category' => 'feature',
                'description' => 'Pre-built campaigns for your off-season, busy-season, and holiday promotions.',
                'tooltip' => 'Pre-built campaigns for your off-season, busy-season, and holiday promotions.',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['branded', 'scale', 'custom'],
                'sort_order' => 240,
                'is_self_serve' => false,
            ],
            [
                'code' => 'unified_inbox',
                'name' => 'Unified inbox',
                'category' => 'feature',
                'description' => 'Every SMS, email, and web message from a customer - threaded in one view.',
                'tooltip' => 'Every SMS, email, and web message from a customer - threaded in one view.',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['scale', 'custom'],
                'sort_order' => 250,
                'is_self_serve' => false,
            ],
            [
                'code' => 'multichannel_campaigns',
                'name' => 'Multi-channel campaigns',
                'category' => 'feature',
                'description' => 'Send the same campaign via SMS and email. System picks best channel per customer.',
                'tooltip' => 'Send the same campaign via SMS and email. System picks best channel per customer.',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['scale', 'custom'],
                'sort_order' => 260,
                'is_self_serve' => false,
            ],
            [
                'code' => 'customer_segmentation',
                'name' => 'Customer segmentation',
                'category' => 'feature',
                'description' => 'Group customers by behavior: loyal, at-risk, new, dormant, high-value.',
                'tooltip' => 'Group customers by behavior: loyal, at-risk, new, dormant, high-value.',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['scale', 'custom'],
                'sort_order' => 270,
                'is_self_serve' => false,
            ],
            [
                'code' => 'behavioral_triggers',
                'name' => 'Behavioral triggers',
                'category' => 'feature',
                'description' => "Auto-message customers based on what they do (or don't do).",
                'tooltip' => "Auto-message customers based on what they do (or don't do).",
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['scale', 'custom'],
                'sort_order' => 280,
                'is_self_serve' => false,
            ],
            [
                'code' => 'lead_capture',
                'name' => 'Lead capture + follow-up',
                'category' => 'feature',
                'description' => 'Capture shoppers not ready to book, auto-nurture them until they are.',
                'tooltip' => 'Capture shoppers not ready to book, auto-nurture them until they are.',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['scale', 'custom'],
                'sort_order' => 290,
                'is_self_serve' => false,
            ],
            [
                'code' => 'custom_domain',
                'name' => 'Custom domain',
                'category' => 'feature',
                'description' => 'Booking page runs at your own domain with zero Intake branding.',
                'tooltip' => 'Booking page runs at your own domain with zero Intake branding.',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['branded', 'scale', 'custom'],
                'sort_order' => 300,
                'is_self_serve' => false,
            ],
            [
                'code' => 'remove_footer',
                'name' => 'Remove Powered by intake footer',
                'category' => 'feature',
                'description' => 'Remove the Intake footer branding from your booking page.',
                'tooltip' => 'Hide the Powered by intake footer on your public booking page.',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['branded', 'scale', 'custom'],
                'sort_order' => 310,
                'is_self_serve' => false,
            ],
            [
                'code' => 'cross_location_profiles',
                'name' => 'Cross-location customer profiles',
                'category' => 'feature',
                'description' => 'Customer recognized at every shop you run, with full history everywhere.',
                'tooltip' => 'Customer recognized at every shop you run, with full history everywhere.',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['scale', 'custom'],
                'sort_order' => 320,
                'is_self_serve' => false,
            ],
            [
                'code' => 'analytics_exports',
                'name' => 'Advanced analytics + exports',
                'category' => 'feature',
                'description' => 'Custom KPI dashboards, scheduled exports, booking patterns, revenue trends.',
                'tooltip' => 'Custom KPI dashboards, scheduled exports, booking patterns, revenue trends.',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['scale', 'custom'],
                'sort_order' => 330,
                'is_self_serve' => false,
            ],
            [
                'code' => 'api_read',
                'name' => 'API read access + webhooks',
                'category' => 'feature',
                'description' => 'Programmatic read access to your data + webhooks for events.',
                'tooltip' => 'Intake auto-talks to your other software (Zapier, Mailchimp, QuickBooks, Slack).',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['scale', 'custom'],
                'sort_order' => 340,
                'is_self_serve' => false,
            ],
            [
                'code' => 'priority_support',
                'name' => 'Priority support',
                'category' => 'feature',
                'description' => 'Faster response times, direct Slack channel, and scheduled check-ins.',
                'tooltip' => 'Faster response times, direct Slack channel, and scheduled check-ins.',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['scale', 'custom'],
                'sort_order' => 350,
                'is_self_serve' => false,
            ],
            [
                'code' => 'guided_import',
                'name' => 'Guided import',
                'category' => 'feature',
                'description' => 'We help map your fields and import customers + 12 months of booking history.',
                'tooltip' => 'We help map your fields and import customers + 12 months of booking history.',
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['branded', 'scale', 'custom'],
                'sort_order' => 360,
                'is_self_serve' => false,
            ],
            [
                'code' => 'whiteglove_migration',
                'name' => 'White-glove competitive migration',
                'category' => 'feature',
                'description' => "We move everything from your old platform (Mindbody, Acuity, etc.) so you don't have to.",
                'tooltip' => "We move everything from your old platform so you don't have to.",
                'price_cents' => 0,
                'billing_cadence' => 'monthly',
                'included_in_plans' => ['scale', 'custom'],
                'sort_order' => 370,
                'is_self_serve' => false,
            ],

            // ONE-TIME ONBOARDING SERVICES
            [
                'code' => 'migration_standard',
                'name' => 'Standard migration',
                'category' => 'onboarding',
                'description' => 'Customers + contacts + tags + 12 months of booking history from Mindbody / Acuity / Booksy. Live in 48hrs.',
                'tooltip' => 'We move your customer list, tags, and 12 months of history over. Live in 48 hours.',
                'price_cents' => 49900,
                'billing_cadence' => 'one_time',
                'included_in_plans' => null,
                'sort_order' => 500,
                'is_self_serve' => false,
            ],
            [
                'code' => 'migration_premium',
                'name' => 'Premium migration',
                'category' => 'onboarding',
                'description' => 'Full historical data: all bookings, payments, staff accounts, custom fields. For shops 2,000+ customers.',
                'tooltip' => 'Full historical data including all bookings, payments, staff accounts, and custom fields.',
                'price_cents' => 99900,
                'billing_cadence' => 'one_time',
                'included_in_plans' => null,
                'sort_order' => 510,
                'is_self_serve' => false,
            ],
            [
                'code' => 'whiteglove_setup',
                'name' => 'White-glove setup',
                'category' => 'onboarding',
                'description' => 'Full migration + branding + intake forms + staff training + go-live support. Turnkey handoff.',
                'tooltip' => 'Full migration plus branding, intake forms, staff training, and go-live support.',
                'price_cents' => 149900,
                'billing_cadence' => 'one_time',
                'included_in_plans' => null,
                'sort_order' => 520,
                'is_self_serve' => false,
            ],
            [
                'code' => 'migration_custom',
                'name' => 'Custom migration',
                'category' => 'onboarding',
                'description' => 'Unusual platforms, massive datasets, complex field mappings. Scoped case-by-case.',
                'tooltip' => 'For unusual source platforms, massive datasets, or complex field mappings. Quoted individually.',
                'price_cents' => 0,
                'billing_cadence' => 'one_time',
                'price_display_override' => 'Quote',
                'included_in_plans' => null,
                'sort_order' => 530,
                'is_self_serve' => false,
            ],
        ];

        foreach ($addons as $row) {
            $row['description'] = $row['description'] ?? null;
            $row['tooltip'] = $row['tooltip'] ?? null;
            $row['price_display_override'] = $row['price_display_override'] ?? null;
            $row['status'] = $row['status'] ?? 'active';
            $row['is_self_serve'] = $row['is_self_serve'] ?? true;
            $row['is_new'] = $row['is_new'] ?? false;
            $row['included_in_plans'] = isset($row['included_in_plans']) && $row['included_in_plans'] !== null
                ? json_encode($row['included_in_plans'])
                : null;
            $row['created_at'] = $now;
            $row['updated_at'] = $now;

            DB::table('addons')->updateOrInsert(
                ['code' => $row['code']],
                $row
            );
        }

        $this->command?->info('AddonCatalogSeeder: seeded ' . count($addons) . ' addons.');
    }
}
