#!/usr/bin/env python3
# patch-158-G9: thin scrollbar on master admin sidebar
"""
Master admin sidebar started showing chunky OS-default scrollbars
when the nav exceeded viewport height (~15+ items + group headers).
Previously these gently scrolled with thin/subtle bars.

Cause: confirmed via process-of-elimination (other apps fine, only
master admin affected) - Filament 3.3.50 sidebar overflow scrollbar
isn't being styled subtly anymore.

Fix: AdminPanelProvider renderHook injects a <style> block into
<head> with thin scrollbar rules scoped to .fi-sidebar-nav. Both
Firefox (scrollbar-width: thin) and WebKit (::-webkit-scrollbar
selectors) covered.

Scoped to .fi-sidebar-nav, so it does not bleed into tenant pages
or other scrollable areas. Hovering the thumb deepens its color
slightly so it remains discoverable.

Single-file PHP patch. No view changes, no migration.
"""
import argparse, base64, pathlib, sys

MARKER = "MARKER-PATCH-158-G9"

FILES = {
    'app/Providers/Filament/AdminPanelProvider.php': """
PD9waHAKCm5hbWVzcGFjZSBBcHBcUHJvdmlkZXJzXEZpbGFtZW50OwoKdXNlIEFwcFxGaWxhbWVu
dFxSZXNvdXJjZXNcQWN0aXZhdGlvblJlc291cmNlOwp1c2UgQXBwXEZpbGFtZW50XFJlc291cmNl
c1xDdXN0b21lclJlc291cmNlOwp1c2UgQXBwXEZpbGFtZW50XFJlc291cmNlc1xEZWJ1Z0xvZ1Jl
c291cmNlOwp1c2UgQXBwXEZpbGFtZW50XFJlc291cmNlc1xMaWNlbnNlUmVzb3VyY2U7CnVzZSBB
cHBcRmlsYW1lbnRcUmVzb3VyY2VzXE1hcmtldGluZ1BhZ2VSZXNvdXJjZTsKdXNlIEFwcFxGaWxh
bWVudFxSZXNvdXJjZXNcQ2hhbmdlbG9nRW50cnlSZXNvdXJjZTsKdXNlIEFwcFxGaWxhbWVudFxS
ZXNvdXJjZXNcUm9hZG1hcEVudHJ5UmVzb3VyY2U7CnVzZSBBcHBcRmlsYW1lbnRcUmVzb3VyY2Vz
XFBsYXRmb3JtTmF2SXRlbVJlc291cmNlOwp1c2UgQXBwXEZpbGFtZW50XFJlc291cmNlc1xTZWN0
aW9uTGlicmFyeVJlc291cmNlOwp1c2UgQXBwXEZpbGFtZW50XFJlc291cmNlc1xTaXRlU2V0dGlu
Z3NSZXNvdXJjZTsKdXNlIEFwcFxGaWxhbWVudFxSZXNvdXJjZXNcVGVuYW50UmVzb3VyY2U7CnVz
ZSBBcHBcRmlsYW1lbnRcUmVzb3VyY2VzXFRlbmFudERvbWFpblJlc291cmNlOyAgLy8gTUFSS0VS
LVBBVENILTExOQp1c2UgQXBwXEZpbGFtZW50XFdpZGdldHNcRGVidWdMb2dIZWFkZXJTdGF0czsK
dXNlIEFwcFxGaWxhbWVudFxXaWRnZXRzXFBsYXRmb3JtU3RhdHNXaWRnZXQ7CnVzZSBBcHBcRmls
YW1lbnRcV2lkZ2V0c1xDdXN0b21Eb21haW5zU3RhdHNXaWRnZXQ7ICAvLyBNQVJLRVItUEFUQ0gt
MTE5CnVzZSBBcHBcRmlsYW1lbnRcV2lkZ2V0c1xTZXJ2ZXJIZWFsdGhXaWRnZXQ7CnVzZSBBcHBc
RmlsYW1lbnRcV2lkZ2V0c1xTdGF0c092ZXJ2aWV3Owp1c2UgQXBwXEZpbGFtZW50XFdpZGdldHNc
T3BlcmF0aW9uYWxIZWFsdGhXaWRnZXQ7ICAvLyBNQVJLRVItUEFUQ0gtMTMyCnVzZSBBcHBcRmls
YW1lbnRcV2lkZ2V0c1xXcFBsdWdpblN0YXRzV2lkZ2V0OyAgICAgICAvLyBNQVJLRVItUEFUQ0gt
MTMyCnVzZSBBcHBcRmlsYW1lbnRcUGFnZXNcVGhlbWVFZGl0b3I7CnVzZSBGaWxhbWVudFxIdHRw
XE1pZGRsZXdhcmVcQXV0aGVudGljYXRlOwp1c2UgRmlsYW1lbnRcSHR0cFxNaWRkbGV3YXJlXERp
c2FibGVCbGFkZUljb25Db21wb25lbnRzOwp1c2UgRmlsYW1lbnRcSHR0cFxNaWRkbGV3YXJlXERp
c3BhdGNoU2VydmluZ0ZpbGFtZW50RXZlbnQ7CnVzZSBGaWxhbWVudFxQYWdlczsKdXNlIEZpbGFt
ZW50XFBhbmVsOwp1c2UgRmlsYW1lbnRcUGFuZWxQcm92aWRlcjsKdXNlIEZpbGFtZW50XFN1cHBv
cnRcQ29sb3JzXENvbG9yOwp1c2UgRmlsYW1lbnRcVmlld1xQYW5lbHNSZW5kZXJIb29rOyAgLy8g
TUFSS0VSLVBBVENILTE1OC1HOQp1c2UgSWxsdW1pbmF0ZVxDb29raWVcTWlkZGxld2FyZVxBZGRR
dWV1ZWRDb29raWVzVG9SZXNwb25zZTsKdXNlIElsbHVtaW5hdGVcQ29va2llXE1pZGRsZXdhcmVc
RW5jcnlwdENvb2tpZXM7CnVzZSBJbGx1bWluYXRlXEZvdW5kYXRpb25cSHR0cFxNaWRkbGV3YXJl
XFZlcmlmeUNzcmZUb2tlbjsKdXNlIElsbHVtaW5hdGVcUm91dGluZ1xNaWRkbGV3YXJlXFN1YnN0
aXR1dGVCaW5kaW5nczsKdXNlIElsbHVtaW5hdGVcU2Vzc2lvblxNaWRkbGV3YXJlXFN0YXJ0U2Vz
c2lvbjsKdXNlIElsbHVtaW5hdGVcU3VwcG9ydFxGYWNhZGVzXEJsYWRlOyAgLy8gTUFSS0VSLVBB
VENILTE1OC1HOQp1c2UgSWxsdW1pbmF0ZVxWaWV3XE1pZGRsZXdhcmVcU2hhcmVFcnJvcnNGcm9t
U2Vzc2lvbjsKCmNsYXNzIEFkbWluUGFuZWxQcm92aWRlciBleHRlbmRzIFBhbmVsUHJvdmlkZXIK
ewogICAgcHVibGljIGZ1bmN0aW9uIHBhbmVsKFBhbmVsICRwYW5lbCk6IFBhbmVsCiAgICB7CiAg
ICAgICAgcmV0dXJuICRwYW5lbAogICAgICAgICAgICAtPmRlZmF1bHQoKQogICAgICAgICAgICAt
PmlkKCdhZG1pbicpCiAgICAgICAgICAgIC0+cGF0aCgnYWRtaW4nKQogICAgICAgICAgICAtPmRv
bWFpbihlbnYoJ0FQUF9ET01BSU4nLCAnaW50YWtlLndvcmtzJykpCiAgICAgICAgICAgIC0+bG9n
aW4oKQogICAgICAgICAgICAtPmNvbG9ycyhbJ3ByaW1hcnknID0+IENvbG9yOjpWaW9sZXRdKQog
ICAgICAgICAgICAtPmJyYW5kTmFtZSgnSW50YWtlJykKICAgICAgICAgICAgLT5yZXNvdXJjZXMo
WwogICAgICAgICAgICAgICAgVGVuYW50UmVzb3VyY2U6OmNsYXNzLAogICAgICAgICAgICAgICAg
VGVuYW50RG9tYWluUmVzb3VyY2U6OmNsYXNzLCAgLy8gTUFSS0VSLVBBVENILTExOQogICAgICAg
ICAgICAgICAgQ3VzdG9tZXJSZXNvdXJjZTo6Y2xhc3MsCiAgICAgICAgICAgICAgICBMaWNlbnNl
UmVzb3VyY2U6OmNsYXNzLAogICAgICAgICAgICAgICAgQWN0aXZhdGlvblJlc291cmNlOjpjbGFz
cywKICAgICAgICAgICAgICAgIE1hcmtldGluZ1BhZ2VSZXNvdXJjZTo6Y2xhc3MsIC8vIG5ldyDi
gJQgbWFya2V0aW5nIHBhZ2UgZWRpdG9yIGVudHJ5CiAgICAgICAgICAgICAgICBQbGF0Zm9ybU5h
dkl0ZW1SZXNvdXJjZTo6Y2xhc3MsIC8vIHBhdGNoIDQ1IOKAlCBuYXYgZWRpdG9yCiAgICAgICAg
ICAgICAgICBDaGFuZ2Vsb2dFbnRyeVJlc291cmNlOjpjbGFzcywKICAgICAgICAgICAgICAgIFJv
YWRtYXBFbnRyeVJlc291cmNlOjpjbGFzcywKICAgICAgICAgICAgICAgIFNpdGVTZXR0aW5nc1Jl
c291cmNlOjpjbGFzcywgLy8gcGF0Y2ggNDUg4oCUIGdsb2JhbCBzaXRlIHNldHRpbmdzCiAgICAg
ICAgICAgICAgICBTZWN0aW9uTGlicmFyeVJlc291cmNlOjpjbGFzcywgLy8gcGF0Y2ggNDUg4oCU
IHNlY3Rpb24gdHlwZSBjYXRhbG9nCiAgICAgICAgICAgICAgICBEZWJ1Z0xvZ1Jlc291cmNlOjpj
bGFzcywKICAgICAgICAgICAgXSkKICAgICAgICAgICAgLT5wYWdlcyhbCiAgICAgICAgICAgICAg
ICAvLyBNQVJLRVItUEFUQ0gtMTM1IOKAlCBjdXN0b20gZGFzaGJvYXJkIHJlcGxhY2VzIFBhZ2Vz
XERhc2hib2FyZAogICAgICAgICAgICAgICAgXEFwcFxGaWxhbWVudFxQYWdlc1xQbGF0Zm9ybURh
c2hib2FyZDo6Y2xhc3MsCiAgICAgICAgICAgICAgICBUaGVtZUVkaXRvcjo6Y2xhc3MsCiAgICAg
ICAgICAgICAgICBcQXBwXEZpbGFtZW50XFBhZ2VzXEJpbGxpbmdDb25maWd1cmF0aW9uOjpjbGFz
cywKICAgICAgICAgICAgICAgIFxBcHBcRmlsYW1lbnRcUGFnZXNcQ2hhbmdlbG9nSW1wb3J0UHJl
dmlldzo6Y2xhc3MsCiAgICAgICAgICAgICAgICBcQXBwXEZpbGFtZW50XFBhZ2VzXEVtYWlsSGVh
bHRoOjpjbGFzcywgIC8vIE1BUktFUi1QQVRDSC0xNDgKICAgICAgICAgICAgXSkKICAgICAgICAg
ICAgLT53aWRnZXRzKFsKICAgICAgICAgICAgICAgIFNlcnZlckhlYWx0aFdpZGdldDo6Y2xhc3Ms
CiAgICAgICAgICAgICAgICBPcGVyYXRpb25hbEhlYWx0aFdpZGdldDo6Y2xhc3MsICAvLyBNQVJL
RVItUEFUQ0gtMTMyCiAgICAgICAgICAgICAgICBQbGF0Zm9ybVN0YXRzV2lkZ2V0OjpjbGFzcywK
ICAgICAgICAgICAgICAgIFdwUGx1Z2luU3RhdHNXaWRnZXQ6OmNsYXNzLCAgICAgICAvLyBNQVJL
RVItUEFUQ0gtMTMyCiAgICAgICAgICAgICAgICBDdXN0b21Eb21haW5zU3RhdHNXaWRnZXQ6OmNs
YXNzLCAgLy8gTUFSS0VSLVBBVENILTExOQogICAgICAgICAgICAgICAgU3RhdHNPdmVydmlldzo6
Y2xhc3MsCiAgICAgICAgICAgICAgICBEZWJ1Z0xvZ0hlYWRlclN0YXRzOjpjbGFzcywKICAgICAg
ICAgICAgXSkKICAgICAgICAgICAgLT5taWRkbGV3YXJlKFsKICAgICAgICAgICAgICAgIEVuY3J5
cHRDb29raWVzOjpjbGFzcywKICAgICAgICAgICAgICAgIEFkZFF1ZXVlZENvb2tpZXNUb1Jlc3Bv
bnNlOjpjbGFzcywKICAgICAgICAgICAgICAgIFN0YXJ0U2Vzc2lvbjo6Y2xhc3MsCiAgICAgICAg
ICAgICAgICBTaGFyZUVycm9yc0Zyb21TZXNzaW9uOjpjbGFzcywKICAgICAgICAgICAgICAgIFZl
cmlmeUNzcmZUb2tlbjo6Y2xhc3MsCiAgICAgICAgICAgICAgICBTdWJzdGl0dXRlQmluZGluZ3M6
OmNsYXNzLAogICAgICAgICAgICAgICAgRGlzYWJsZUJsYWRlSWNvbkNvbXBvbmVudHM6OmNsYXNz
LAogICAgICAgICAgICAgICAgRGlzcGF0Y2hTZXJ2aW5nRmlsYW1lbnRFdmVudDo6Y2xhc3MsCiAg
ICAgICAgICAgIF0pCiAgICAgICAgICAgIC8vIE1BUktFUi1QQVRDSC0xNTgtRzkg4oCUIFJlc3Rv
cmUgc3VidGxlIHNjcm9sbGJhciBzdHlsaW5nIG9uIHRoZSBtYXN0ZXItYWRtaW4KICAgICAgICAg
ICAgLy8gc2lkZWJhci4gRmlsYW1lbnQncyBzaWRlYmFyIHNjcm9sbHMgd2hlbiBuYXYgaXRlbXMg
ZXhjZWVkIHZpZXdwb3J0IGhlaWdodAogICAgICAgICAgICAvLyAod2hpY2ggaGFwcGVucyBvbmNl
IHRoZSBwYW5lbCBoYXMgfjE1KyBpdGVtcyksIGFuZCBhIHJlY2VudCBjaGFuZ2Ugc3RhcnRlZAog
ICAgICAgICAgICAvLyBzaG93aW5nIHRoZSBPUyBkZWZhdWx0IGNodW5reSBzY3JvbGxiYXIuIFRo
aXMgaW5qZWN0cyB0aGluL2RpbSBzdHlsaW5nCiAgICAgICAgICAgIC8vIHNjb3BlZCB0byB0aGUg
c2lkZWJhciBuYXYgc28gaXQgZ2VudGx5IHNjcm9sbHMgd2l0aG91dCB2aXN1YWxseSBkb21pbmF0
aW5nLgogICAgICAgICAgICAtPnJlbmRlckhvb2soCiAgICAgICAgICAgICAgICBQYW5lbHNSZW5k
ZXJIb29rOjpIRUFEX0VORCwKICAgICAgICAgICAgICAgIGZuICgpOiBzdHJpbmcgPT4gQmxhZGU6
OnJlbmRlcig8PDwnSFRNTCcKICAgICAgICAgICAgICAgIDxzdHlsZT4KICAgICAgICAgICAgICAg
ICAgLyogRmlyZWZveCAqLwogICAgICAgICAgICAgICAgICAuZmktc2lkZWJhci1uYXYgewogICAg
ICAgICAgICAgICAgICAgIHNjcm9sbGJhci13aWR0aDogdGhpbjsKICAgICAgICAgICAgICAgICAg
ICBzY3JvbGxiYXItY29sb3I6IHJnYmEoMTI3LDEyNywxMjcsMC4yNSkgdHJhbnNwYXJlbnQ7CiAg
ICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICAgLyogV2ViS2l0IChTYWZhcmksIENo
cm9tZSkgKi8KICAgICAgICAgICAgICAgICAgLmZpLXNpZGViYXItbmF2Ojotd2Via2l0LXNjcm9s
bGJhciB7IHdpZHRoOiA2cHg7IH0KICAgICAgICAgICAgICAgICAgLmZpLXNpZGViYXItbmF2Ojot
d2Via2l0LXNjcm9sbGJhci10cmFjayB7IGJhY2tncm91bmQ6IHRyYW5zcGFyZW50OyB9CiAgICAg
ICAgICAgICAgICAgIC5maS1zaWRlYmFyLW5hdjo6LXdlYmtpdC1zY3JvbGxiYXItdGh1bWIgewog
ICAgICAgICAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYmEoMTI3LDEyNywxMjcsMC4yNSk7CiAg
ICAgICAgICAgICAgICAgICAgYm9yZGVyLXJhZGl1czogM3B4OwogICAgICAgICAgICAgICAgICB9
CiAgICAgICAgICAgICAgICAgIC5maS1zaWRlYmFyLW5hdjo6LXdlYmtpdC1zY3JvbGxiYXItdGh1
bWI6aG92ZXIgewogICAgICAgICAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYmEoMTI3LDEyNywx
MjcsMC40NSk7CiAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgIDwvc3R5bGU+CiAg
ICAgICAgICAgICAgICBIVE1MKQogICAgICAgICAgICApCiAgICAgICAgICAgIC0+YXV0aEd1YXJk
KCd3ZWInKQogICAgICAgICAgICAtPmF1dGhNaWRkbGV3YXJlKFsKICAgICAgICAgICAgICAgIEF1
dGhlbnRpY2F0ZTo6Y2xhc3MsCiAgICAgICAgICAgIF0pOwogICAgfQp9Cg==
""",
}

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("root")
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    root = pathlib.Path(a.root).resolve()
    if not (root / "routes" / "web.php").exists():
        print(f"ERROR: not an intake repo: {root}", file=sys.stderr)
        sys.exit(2)
    mode = "APPLY" if a.apply else "DRY-RUN"
    print(f"=== patch-158-G9 [{mode}] target={root} ===\n")

    any_changed = False
    for rel, b64 in FILES.items():
        p = root / rel
        if not p.exists():
            print(f"ERROR: missing {rel}", file=sys.stderr); sys.exit(2)
        if MARKER.encode() in p.read_bytes():
            print(f"  already_applied: {rel}")
            continue
        if a.apply:
            p.write_bytes(base64.b64decode(b64.replace("\n", "")))
        print(f"  {'written' if a.apply else 'would_write'}: {rel}")
        any_changed = True

    if a.apply and any_changed:
        print()
        print("Done. Next:")
        print("  git add app/")
        print("  git commit -m \"patch-158-G9: thin scrollbar on master admin sidebar\"")
        print("  git push")
        print()
        print("On droplet:")
        print("  git pull && php artisan optimize:clear")
        print("  systemctl stop php8.3-fpm && sleep 2 && systemctl start php8.3-fpm")

if __name__ == "__main__":
    main()
