<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Adds accounting-export fields to tenant_special_orders.
 *
 * THREE FIELDS, distinct purposes:
 *
 *   po_number              — OUR outbound PO number. Generated by us
 *                            when status transitions from needed → ordered.
 *                            Format is tenant-configurable (e.g. "BH-PO-2401")
 *                            but stored as freeform string for flexibility.
 *
 *   vendor_invoice_number  — the number on the vendor's invoice. Filled at
 *                            or near receiving. Primary key for accounting
 *                            export matching (QuickBooks vendor bills, Xero
 *                            bills, CSV for accountant).
 *
 *   vendor_invoice_date    — date stamped on the vendor's invoice. NOT the
 *                            same as arrived_at (when WE physically got the
 *                            parts). Accounting periods key off this.
 *                            DATE type — hour precision is noise here.
 *
 * Distinction reminder:
 *   po_number          — what WE call this order, going outbound to the vendor
 *   vendor_reference   — what the VENDOR calls this order, returning to us
 *                        (already shipped in patch 82)
 *   vendor_invoice_*   — what the VENDOR'S BILLING SYSTEM calls this order
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('tenant_special_orders', function (Blueprint $table) {
            $table->string('po_number', 64)
                ->nullable()
                ->after('vendor_reference');

            $table->string('vendor_invoice_number', 64)
                ->nullable()
                ->after('po_number');

            $table->date('vendor_invoice_date')
                ->nullable()
                ->after('vendor_invoice_number');

            // Lookup index for accounting export queries — filtered by
            // invoice date range. Only matters when invoice_number is
            // set, so partial-like behavior via NULL filtering at the
            // query level is fine without a partial index.
            $table->index(
                ['tenant_id', 'vendor_invoice_date'],
                'tso_tenant_invdate_idx'
            );
        });
    }

    public function down(): void
    {
        Schema::table('tenant_special_orders', function (Blueprint $table) {
            $table->dropIndex('tso_tenant_invdate_idx');
            $table->dropColumn(['po_number', 'vendor_invoice_number', 'vendor_invoice_date']);
        });
    }
};
